[colors]
background       = '#000'
black            = '#000000'
blue             = '#0A2FC4'
cursor           = 'rgba(248,28,229,0.8)'
cyan             = '#20C5C6'
foreground       = '#fff'
green            = '#50fa7b'
magenta          = '#FF79C6'
red              = '#C51E14'
tabs             = '#494c62'
tabs-active      = '#6a6e8e'
white            = '#C7C7C7'
yellow           = '#F1FA8C'
dim-black        = '#393C4b'
dim-blue         = '#AE7BF8'
dim-cyan         = '#69C3dE'
dim-foreground   = '#dfdfd9'
dim-green        = '#06572F'
dim-magenta      = '#FF60BB'
dim-red          = '#FF3C3C'
dim-white        = '#EFEFE1'
dim-yellow       = '#E6A003'
light-black      = '#686868'
light-blue       = '#6A76FB'
light-cyan       = '#68FDFE'
light-foreground = '#f8f8f1'
light-green      = '#67F86F'
light-magenta    = '#FF92DF'
light-red        = '#FD6F6B'
light-white      = '#FFFFFF'
light-yellow     = '#FFFA72'
